from CommandLineDialog import *
from MenuDialog import *
from OptionDialog import *
from CollectionDialog import *
from NewUserDialog import *
from NewMovieDialog import *
from NewShowtimeDialog import *
from NewTimeslotDialog import *
from ReserveTicketDialog import *
from QuitDialog import *